// 20+ realistic AI-generated campaign suggestions
// Each campaign has all fields required by the Campaign schema

export const CAMPAIGN_DATA = [
  {
    id: "c1",
    title: "Diwali Flash Sale 2024",
    description: "Celebrate the Festival of Lights with exclusive deals up to 60% off on electronics and home decor. Drive massive conversions with culturally relevant visuals.",
    audience: "Indian consumers aged 25–45, urban households",
    platform: "Instagram",
    budget: "High",
    category: "Ecommerce",
    tags: ["festival", "sale", "india", "diwali", "flash-sale"],
    cta: "Shop Now & Save 60%",
    engagementRate: 8.4,
    performanceScore: 94,
    createdAt: "2024-10-15T10:00:00Z",
  },
  {
    id: "c2",
    title: "Ramadan Gifting Guide",
    description: "Inspire giving during the holy month with curated gift bundles. Localized Arabic copy and warm, premium visuals for the MENA market.",
    audience: "MENA consumers aged 22–40, gift buyers",
    platform: "Facebook",
    budget: "Medium",
    category: "Ecommerce",
    tags: ["ramadan", "gifts", "mena", "arabic", "premium"],
    cta: "Discover Perfect Gifts",
    engagementRate: 6.9,
    performanceScore: 88,
    createdAt: "2024-03-10T08:00:00Z",
  },
  {
    id: "c3",
    title: "Black Friday Countdown",
    description: "Build FOMO with a 7-day countdown campaign. Progressive discounts leading to 70% off on Black Friday itself. Ideal for high-AOV products.",
    audience: "USA shoppers aged 18–35, deal hunters",
    platform: "TikTok",
    budget: "High",
    category: "Ecommerce",
    tags: ["black-friday", "fomo", "countdown", "usa", "deals"],
    cta: "Start Saving Now",
    engagementRate: 11.2,
    performanceScore: 97,
    createdAt: "2024-11-01T09:00:00Z",
  },
  {
    id: "c4",
    title: "New Year Fitness Push",
    description: "Capitalize on New Year resolutions with a 30-day fitness challenge campaign. Partner with micro-influencers for authentic UGC content.",
    audience: "Fitness enthusiasts aged 20–38, resolutioners",
    platform: "Instagram",
    budget: "Medium",
    category: "Fitness",
    tags: ["fitness", "new-year", "challenge", "health", "ugc"],
    cta: "Start Your 30-Day Challenge",
    engagementRate: 7.8,
    performanceScore: 85,
    createdAt: "2024-12-28T07:00:00Z",
  },
  {
    id: "c5",
    title: "Spring Fashion Drop",
    description: "Launch the spring collection with bright, editorial-style Reels. Target fashion-forward consumers with size-inclusive messaging and trend keywords.",
    audience: "Fashion lovers aged 18–30, trend followers",
    platform: "Instagram",
    budget: "Medium",
    category: "Fashion",
    tags: ["fashion", "spring", "collection", "ootd", "reels"],
    cta: "Shop the New Collection",
    engagementRate: 9.1,
    performanceScore: 91,
    createdAt: "2024-02-20T11:00:00Z",
  },
  {
    id: "c6",
    title: "SaaS Product Launch – B2B",
    description: "Targeted LinkedIn campaign announcing your SaaS tool launch. Use thought-leadership content, live demos, and gated case studies to generate qualified leads.",
    audience: "B2B decision makers, CTOs, Marketing Directors",
    platform: "LinkedIn",
    budget: "High",
    category: "SaaS",
    tags: ["saas", "b2b", "launch", "linkedin", "thought-leadership"],
    cta: "Book a Free Demo",
    engagementRate: 3.4,
    performanceScore: 82,
    createdAt: "2024-04-05T14:00:00Z",
  },
  {
    id: "c7",
    title: "German Summer Discount Week",
    description: "Drive conversions in Germany with localized 'Sommerrabatt' messaging. Emphasize quality, precision, and value. Germans respond well to data-backed claims.",
    audience: "German consumers aged 30–55, quality seekers",
    platform: "Google Ads",
    budget: "High",
    category: "Ecommerce",
    tags: ["germany", "summer", "localized", "quality", "discount"],
    cta: "Jetzt Sparen – Shop Now",
    engagementRate: 4.2,
    performanceScore: 79,
    createdAt: "2024-06-01T09:00:00Z",
  },
  {
    id: "c8",
    title: "Skincare Routine Series",
    description: "5-part educational email series on morning skincare routines. Promote hero products with dermatologist quotes and before/after results.",
    audience: "Beauty enthusiasts aged 22–40, skincare-conscious women",
    platform: "Email",
    budget: "Low",
    category: "Beauty",
    tags: ["skincare", "email", "education", "routine", "beauty"],
    cta: "Get Your Free Skincare Guide",
    engagementRate: 28.4,
    performanceScore: 87,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "c9",
    title: "Food Delivery Weekend Promo",
    description: "Drive weekend orders with limited-time 30% off coupon via TikTok food creators. Short-form video of mouth-watering dishes converts best on this platform.",
    audience: "Urban dwellers aged 18–35, food lovers",
    platform: "TikTok",
    budget: "Low",
    category: "Food",
    tags: ["food", "delivery", "weekend", "promo", "coupon"],
    cta: "Order Now – 30% Off This Weekend",
    engagementRate: 14.7,
    performanceScore: 90,
    createdAt: "2024-07-12T16:00:00Z",
  },
  {
    id: "c10",
    title: "Tech Gadget Pre-Order Campaign",
    description: "Build hype before launch with exclusive early-access offers. Use countdown timers, unboxing preview videos, and influencer seeding to create buzz.",
    audience: "Tech enthusiasts aged 20–40, early adopters",
    platform: "YouTube",
    budget: "High",
    category: "Tech",
    tags: ["tech", "gadgets", "pre-order", "launch", "influencer"],
    cta: "Reserve Yours – Limited Units",
    engagementRate: 5.9,
    performanceScore: 93,
    createdAt: "2024-09-01T08:00:00Z",
  },
  {
    id: "c11",
    title: "Valentine's Day Bundle Push",
    description: "Promote couple gift bundles with romantic email sequences. Segment by relationship status for hyper-personalized messaging.",
    audience: "Couples aged 22–40, gift buyers",
    platform: "Email",
    budget: "Medium",
    category: "Ecommerce",
    tags: ["valentines", "bundle", "romantic", "gift", "email"],
    cta: "Surprise Your Partner Today",
    engagementRate: 31.2,
    performanceScore: 89,
    createdAt: "2024-02-01T12:00:00Z",
  },
  {
    id: "c12",
    title: "Fitness App Retargeting",
    description: "Re-engage lapsed users with a personalized comeback offer. Show users their past progress stats and offer a 3-month discount to re-activate subscriptions.",
    audience: "Former subscribers aged 22–38, fitness-conscious",
    platform: "Facebook",
    budget: "Medium",
    category: "Fitness",
    tags: ["fitness", "retargeting", "app", "reactivation", "discount"],
    cta: "Come Back – 3 Months for ₹499",
    engagementRate: 6.3,
    performanceScore: 76,
    createdAt: "2024-05-10T09:00:00Z",
  },
  {
    id: "c13",
    title: "Luxury Fashion: Japan Launch",
    description: "Premium brand launch in Japan using aspirational imagery and minimalist aesthetics aligned with Japanese design sensibilities. High-production editorial style.",
    audience: "Japanese luxury consumers aged 28–50",
    platform: "Instagram",
    budget: "High",
    category: "Fashion",
    tags: ["luxury", "japan", "fashion", "premium", "launch"],
    cta: "Explore the Collection",
    engagementRate: 4.7,
    performanceScore: 86,
    createdAt: "2024-08-20T10:00:00Z",
  },
  {
    id: "c14",
    title: "SaaS Free Trial Push – LinkedIn",
    description: "Target startup founders and product managers with '14-Day Free Trial' ads. Use social proof (# of companies using product) and ROI-focused copy.",
    audience: "Startup founders, Product Managers, B2B buyers",
    platform: "LinkedIn",
    budget: "Medium",
    category: "SaaS",
    tags: ["saas", "free-trial", "b2b", "roi", "startup"],
    cta: "Start Your Free 14-Day Trial",
    engagementRate: 2.8,
    performanceScore: 81,
    createdAt: "2024-03-22T13:00:00Z",
  },
  {
    id: "c15",
    title: "Google Shopping: Beauty Bestsellers",
    description: "Run Google Shopping ads for top-selling beauty products. Optimize titles with high-intent keywords and use promo labels for extra click-through.",
    audience: "Beauty buyers actively searching online, aged 20–45",
    platform: "Google Ads",
    budget: "Medium",
    category: "Beauty",
    tags: ["beauty", "google", "shopping", "bestsellers", "ppc"],
    cta: "Shop Bestsellers",
    engagementRate: 3.9,
    performanceScore: 83,
    createdAt: "2024-04-18T11:00:00Z",
  },
  {
    id: "c16",
    title: "Food Brand Awareness: TikTok Chef",
    description: "Partner with 5 micro-influencer chefs to create authentic recipes using your product. Native UGC content feels organic and drives massive discovery.",
    audience: "Home cooks aged 22–40, food explorers",
    platform: "TikTok",
    budget: "Low",
    category: "Food",
    tags: ["food", "ugc", "chef", "tiktok", "recipe"],
    cta: "Try the Recipe Yourself",
    engagementRate: 18.3,
    performanceScore: 92,
    createdAt: "2024-06-30T17:00:00Z",
  },
  {
    id: "c17",
    title: "Back to School Tech Bundle",
    description: "Target parents buying back-to-school supplies with laptop + accessory bundles. Early-August timing maximizes intent. Bundle discounts drive higher AOV.",
    audience: "Parents aged 30–50, students aged 15–22",
    platform: "Facebook",
    budget: "High",
    category: "Tech",
    tags: ["tech", "back-to-school", "bundle", "laptop", "students"],
    cta: "Get the School Bundle – Save ₹3000",
    engagementRate: 5.8,
    performanceScore: 88,
    createdAt: "2024-07-25T08:00:00Z",
  },
  {
    id: "c18",
    title: "Ecommerce Email Win-Back",
    description: "Recover dormant customers with a 3-email win-back sequence. Email 1: 'We miss you', Email 2: 15% off, Email 3: 25% off final offer. Proven 22% reactivation rate.",
    audience: "Lapsed customers, last purchase 90+ days ago",
    platform: "Email",
    budget: "Low",
    category: "Ecommerce",
    tags: ["email", "win-back", "reactivation", "sequence", "discount"],
    cta: "Claim Your Welcome-Back Offer",
    engagementRate: 22.1,
    performanceScore: 91,
    createdAt: "2024-08-05T09:00:00Z",
  },
  {
    id: "c19",
    title: "Influencer Fitness Apparel Drop",
    description: "Limited-edition fitness apparel drop with 3 macro-influencers. 48-hour exclusive access for followers, then public sale. Creates urgency and authentic demand.",
    audience: "Fitness enthusiasts aged 18–32, followers of fitness influencers",
    platform: "Instagram",
    budget: "High",
    category: "Fitness",
    tags: ["fitness", "influencer", "drop", "apparel", "limited"],
    cta: "Get Early Access Now",
    engagementRate: 10.6,
    performanceScore: 96,
    createdAt: "2024-09-12T10:00:00Z",
  },
  {
    id: "c20",
    title: "Midnight Beauty Sale",
    description: "Exclusive midnight-to-6am flash sale with surprise product bundles revealed hourly. Creates excitement, urgency, and social sharing. Works best with loyal community.",
    audience: "Night owls, beauty loyal customers aged 18–35",
    platform: "Instagram",
    budget: "Medium",
    category: "Beauty",
    tags: ["beauty", "flash-sale", "midnight", "exclusive", "community"],
    cta: "Join the Midnight Sale",
    engagementRate: 12.4,
    performanceScore: 95,
    createdAt: "2024-10-02T23:00:00Z",
  },
  {
    id: "c21",
    title: "B2B SaaS Case Study Campaign",
    description: "Drive enterprise leads with a detailed industry-specific case study campaign. Use LinkedIn document ads and retargeting to push prospects through the funnel.",
    audience: "Enterprise buyers, VP-level, IT and Marketing departments",
    platform: "LinkedIn",
    budget: "High",
    category: "SaaS",
    tags: ["saas", "b2b", "case-study", "enterprise", "linkedin"],
    cta: "Download the Full Case Study",
    engagementRate: 2.1,
    performanceScore: 78,
    createdAt: "2024-05-28T14:00:00Z",
  },
  {
    id: "c22",
    title: "Korean Beauty Brand Launch – USA",
    description: "Introduce a K-beauty brand to the US market via TikTok and Instagram Reels. Leverage K-beauty trend with before/after results and skincare routine integration.",
    audience: "US beauty consumers aged 18–35 interested in K-beauty",
    platform: "TikTok",
    budget: "Medium",
    category: "Beauty",
    tags: ["k-beauty", "usa", "skincare", "launch", "trend"],
    cta: "Try K-Beauty Today",
    engagementRate: 15.8,
    performanceScore: 92,
    createdAt: "2024-07-08T10:00:00Z",
  },
  {
    id: "c23",
    title: "Google Ads Ecommerce ROAS Booster",
    description: "Smart Shopping campaign targeting high-intent buyers searching for your product category. Use Performance Max with audience signals for maximum conversion.",
    audience: "High-intent shoppers actively searching on Google",
    platform: "Google Ads",
    budget: "High",
    category: "Ecommerce",
    tags: ["google", "pmax", "roas", "shopping", "conversion"],
    cta: "Shop Now – Free Shipping",
    engagementRate: 4.5,
    performanceScore: 84,
    createdAt: "2024-06-15T09:00:00Z",
  },
  {
    id: "c24",
    title: "Holiday Food Gifting Campaign",
    description: "Premium food hamper gifting campaign for Christmas and New Year. Email-first approach with gift customization tool. Drives high AOV and repeat purchase.",
    audience: "Corporate gift buyers, families aged 30–55",
    platform: "Email",
    budget: "Medium",
    category: "Food",
    tags: ["food", "holiday", "gifting", "christmas", "hamper"],
    cta: "Build Your Custom Hamper",
    engagementRate: 26.7,
    performanceScore: 89,
    createdAt: "2024-11-20T10:00:00Z",
  },
];

// Platform color and icon mapping
export const PLATFORM_META = {
  Instagram:  { color: "bg-pink-100 text-pink-700",    icon: "📸" },
  Facebook:   { color: "bg-blue-100 text-blue-700",    icon: "👥" },
  TikTok:     { color: "bg-gray-900 text-white",       icon: "🎵" },
  LinkedIn:   { color: "bg-sky-100 text-sky-700",      icon: "💼" },
  Email:      { color: "bg-green-100 text-green-700",  icon: "📧" },
  "Google Ads":{ color: "bg-yellow-100 text-yellow-700", icon: "🔍" },
  YouTube:    { color: "bg-red-100 text-red-700",      icon: "▶️" },
};

// Budget color mapping
export const BUDGET_META = {
  Low:    "bg-green-100 text-green-700",
  Medium: "bg-yellow-100 text-yellow-700",
  High:   "bg-red-100 text-red-700",
};

// Score color bands
export function getScoreColor(score) {
  if (score >= 90) return "text-green-600";
  if (score >= 75) return "text-yellow-600";
  return "text-red-500";
}

export function getScoreBg(score) {
  if (score >= 90) return "bg-green-500";
  if (score >= 75) return "bg-yellow-400";
  return "bg-red-400";
}
